version: "3.9"


services:
  db:
    image: postgres:17-alpine
    container_name: todo_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: todo-server
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      PORT: 3000
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "3000:3000"
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: todo-client
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    