# - STAGE - 1 - Build -

FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY prisma.config.ts ./

RUN npm ci

COPY . .

RUN npx prisma generate

RUN npm run build

# - STAGE - 2 - Build -

FROM node:22-alpine AS production

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY prisma.config.ts ./

RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

COPY --from=builder /app/src/generated ./src/generated

RUN npx prisma generate

EXPOSE 3000

CMD ["sh","-c","npx prisma migrate deploy && node dist/server.js"]