name: Deploy Todo Application on AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_GIT_ACTIONS_PVT_KEY }}
          port: 22
          known_hosts: ${{secrets.EC2_KNOWN_HOSTS}}
          script: |
            cd /home/ubuntu/aws-todo-app
            git pull origin main
            docker compose up -d --build